FROM python:3-windowsservercore

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV FLASK_CONFIG=production

CMD [ "python", "./run.py" ]
