import os
from crewai import Agent, Task, Crew, Process, LLM

ollama_llm = LLM(
    model="ollama/llama3.2",
    base_url="http://localhost:11434"
)


# Define your agents
researcher = Agent(
    role="Researcher",
    goal="Conduct thorough research and analysis on AI and AI agents",
    backstory="You're an expert researcher, specialized in technology, software engineering, AI, and startups. You work as a freelancer and are currently researching for a new client.",
    allow_delegation=False,
    llm=ollama_llm,
    verbose=True,
)

writer = Agent(
    role="Senior Writer",
    goal="Create compelling content about AI and AI agents",
    backstory="You're a senior writer, specialized in technology, software engineering, AI, and startups. You work as a freelancer and are currently writing content for a new client.",
    allow_delegation=False,
    llm=ollama_llm,
    verbose=True,
)

# Define your task
task = Task(
    description="Generate a list of 5 interesting ideas for an article, then write one captivating paragraph for each idea that showcases the potential of a full article on this topic. Return the list of ideas with their paragraphs and your notes.",
    expected_output="5 bullet points, each with a paragraph and accompanying notes.",
    agent=researcher,
)

blog_post = Task(
    description="Write a blog post about the ideas generated by the Researcher. The blog post should be engaging and informative, targeting a general audience interested in AI.",
    expected_output="A well-structured blog post that includes the ideas and their paragraphs, along with an introduction and conclusion.", 
    agent=writer,
)

# Instantiate your crew with a custom manager
crew = Crew(
    agents=[researcher, writer],
    tasks=[task, blog_post],
    verbose=1,
    llm=ollama_llm,
)

# Start the crew's work
result = crew.kickoff()
print(result)