# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ipv4gui.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 209)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.lblRede = QtWidgets.QLabel(self.centralwidget)
        self.lblRede.setText("")
        self.lblRede.setObjectName("lblRede")
        self.gridLayout.addWidget(self.lblRede, 5, 1, 1, 1)
        self.lblMascara = QtWidgets.QLabel(self.centralwidget)
        self.lblMascara.setText("")
        self.lblMascara.setObjectName("lblMascara")
        self.gridLayout.addWidget(self.lblMascara, 4, 1, 1, 1)
        self.lblPrefixo = QtWidgets.QLabel(self.centralwidget)
        self.lblPrefixo.setText("")
        self.lblPrefixo.setObjectName("lblPrefixo")
        self.gridLayout.addWidget(self.lblPrefixo, 7, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 7, 0, 1, 1)
        self.lblBroadcast = QtWidgets.QLabel(self.centralwidget)
        self.lblBroadcast.setText("")
        self.lblBroadcast.setObjectName("lblBroadcast")
        self.gridLayout.addWidget(self.lblBroadcast, 6, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 8, 0, 1, 1)
        self.lblNumeroIPs = QtWidgets.QLabel(self.centralwidget)
        self.lblNumeroIPs.setText("")
        self.lblNumeroIPs.setObjectName("lblNumeroIPs")
        self.gridLayout.addWidget(self.lblNumeroIPs, 8, 1, 1, 1)
        self.txtIP = QtWidgets.QLineEdit(self.centralwidget)
        self.txtIP.setObjectName("txtIP")
        self.gridLayout.addWidget(self.txtIP, 0, 1, 1, 1)
        self.txtPrefixo = QtWidgets.QLineEdit(self.centralwidget)
        self.txtPrefixo.setObjectName("txtPrefixo")
        self.gridLayout.addWidget(self.txtPrefixo, 1, 1, 1, 1)
        self.txtMascara = QtWidgets.QLineEdit(self.centralwidget)
        self.txtMascara.setObjectName("txtMascara")
        self.gridLayout.addWidget(self.txtMascara, 2, 1, 1, 1)
        self.lblIP = QtWidgets.QLabel(self.centralwidget)
        self.lblIP.setText("")
        self.lblIP.setObjectName("lblIP")
        self.gridLayout.addWidget(self.lblIP, 3, 1, 1, 1)
        self.btnCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.btnCalcular.setObjectName("btnCalcular")
        self.gridLayout.addWidget(self.btnCalcular, 0, 4, 1, 1)
        self.btnLimpar = QtWidgets.QPushButton(self.centralwidget)
        self.btnLimpar.setObjectName("btnLimpar")
        self.gridLayout.addWidget(self.btnLimpar, 1, 4, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cálculo de Redes IPv4"))
        self.label_3.setText(_translate("MainWindow", "Informe o prefixo:"))
        self.label.setText(_translate("MainWindow", "Informe o IP:"))
        self.label_2.setText(_translate("MainWindow", "Informe a máscara:"))
        self.label_4.setText(_translate("MainWindow", "IP:"))
        self.label_6.setText(_translate("MainWindow", "Máscara:"))
        self.label_8.setText(_translate("MainWindow", "Rede:"))
        self.label_12.setText(_translate("MainWindow", "Prefixo:"))
        self.label_10.setText(_translate("MainWindow", "Broadcast:"))
        self.label_14.setText(_translate("MainWindow", "Números de IPs da rede:"))
        self.btnCalcular.setText(_translate("MainWindow", "Calcular"))
        self.btnLimpar.setText(_translate("MainWindow", "Limpar"))
