# Generated by Django 6.0.1 on 2026-01-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migratedbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age_persisted',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
