# Generated by Django 6.0.1 on 2026-01-29 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('migratedbs', '0002_person_age_persisted_alter_personmysql_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_autor', models.CharField(max_length=200)),
                ('nom_alias', models.CharField(max_length=200)),
                ('partido', models.CharField(blank=True, max_length=200, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
                'db_table': 'ric_autor',
            },
        ),
        migrations.CreateModel(
            name='EtapaFluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etapa_fluxo', models.CharField(max_length=30)),
                ('nom_alias', models.CharField(max_length=30)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Etapa do Fluxo',
                'verbose_name_plural': 'Etapas do Fluxo',
                'db_table': 'ric_etapa_fluxo',
            },
        ),
        migrations.CreateModel(
            name='OrigemRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_orig_requerimento', models.CharField(db_column='nom_origem_requerimento', max_length=50)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Origem do Requerimento',
                'verbose_name_plural': 'Origens do Requerimento',
                'db_table': 'ric_origem_requerimento',
            },
        ),
        migrations.CreateModel(
            name='StatusRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_status_requerimento', models.CharField(max_length=50)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status do Requerimento',
                'verbose_name_plural': 'Status dos Requerimentos',
                'db_table': 'ric_status_requerimento',
            },
        ),
        migrations.CreateModel(
            name='TematicaRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tematica_requerimento', models.CharField(max_length=50)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Temática do Requerimento',
                'verbose_name_plural': 'Temáticas do Requerimento',
                'db_table': 'ric_tematica_requerimento',
            },
        ),
        migrations.CreateModel(
            name='TipoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_autor', models.CharField(max_length=50)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Autor',
                'verbose_name_plural': 'Tipos de Autor',
                'db_table': 'ric_tipo_autor',
            },
        ),
        migrations.CreateModel(
            name='TipoRequerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_requerimento', models.CharField(max_length=50)),
                ('sigla_tipo_requerimento', models.CharField(max_length=3)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Requerimento',
                'verbose_name_plural': 'Tipos de Requerimento',
                'db_table': 'ric_tipo_requerimento',
            },
        ),
        migrations.CreateModel(
            name='TipoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tipo_resposta', models.CharField(max_length=50)),
                ('nom_alias', models.CharField(max_length=50)),
                ('flg_desativado', models.BooleanField(default=False)),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Resposta',
                'verbose_name_plural': 'Tipos de Resposta',
                'db_table': 'ric_tipo_resposta',
            },
        ),
        migrations.CreateModel(
            name='Requerimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
                ('num_requerimento', models.IntegerField()),
                ('ano_requerimento', models.IntegerField()),
                ('num_oficio', models.TextField()),
                ('data_recebimento_pr', models.DateField()),
                ('prazo_final_resposta_cn', models.DateField()),
                ('processo_sei_envio_cc', models.CharField(max_length=35)),
                ('processo_sei_resposta_cc', models.CharField(max_length=35)),
                ('dsc_objeto_requerimento', models.TextField()),
                ('unidades_consultadas', models.JSONField()),
                ('status_congresso', models.TextField()),
                ('ementa', models.TextField()),
                ('andamento_cc', models.TextField()),
                ('prazo_etapa', models.TextField(blank=True, null=True)),
                ('dsc_resumo', models.TextField(blank=True, null=True)),
                ('dsc_observacoes', models.TextField(blank=True, null=True)),
                ('data_resposta_demandante', models.DateField()),
                ('link_congresso', models.TextField(blank=True, null=True)),
                ('link_inteiro_teor', models.TextField(blank=True, null=True)),
                ('etapa_fluxo', models.ForeignKey(blank=True, db_column='etapa_fluxo_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.etapafluxo')),
                ('origem_requerimento', models.ForeignKey(db_column='origem_requerimento_id', on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.origemrequerimento')),
            ],
            options={
                'verbose_name': 'Requerimento',
                'verbose_name_plural': 'Requerimentos',
                'db_table': 'ric_requerimento',
            },
        ),
        migrations.CreateModel(
            name='RequerimentoAutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dat_atualizacao', models.DateTimeField()),
                ('flg_ativo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(db_column='autor_id', on_delete=django.db.models.deletion.CASCADE, related_name='requerimentos_vinculos', to='migratedbs.autor')),
                ('requerimento', models.ForeignKey(db_column='requerimento_id', on_delete=django.db.models.deletion.CASCADE, related_name='autores_vinculos', to='migratedbs.requerimento')),
            ],
            options={
                'verbose_name': 'Autor do Requerimento',
                'verbose_name_plural': 'Autores do Requerimento',
                'db_table': 'ric_requerimento_autor',
            },
        ),
        migrations.AddField(
            model_name='requerimento',
            name='autores',
            field=models.ManyToManyField(related_name='requerimentos', through='migratedbs.RequerimentoAutor', to='migratedbs.autor'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='status_requerimento',
            field=models.ForeignKey(db_column='status_requerimento_id', on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.statusrequerimento'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='tematica',
            field=models.ForeignKey(db_column='tematica_id', on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.tematicarequerimento'),
        ),
        migrations.AddField(
            model_name='autor',
            name='tipo_autor',
            field=models.ForeignKey(db_column='tipo_autor_id', on_delete=django.db.models.deletion.PROTECT, related_name='autores', to='migratedbs.tipoautor'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='tipo_requerimento',
            field=models.ForeignKey(db_column='tipo_requerimento_id', on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.tiporequerimento'),
        ),
        migrations.AddField(
            model_name='requerimento',
            name='tipo_resposta',
            field=models.ForeignKey(db_column='tipo_resposta_id', on_delete=django.db.models.deletion.PROTECT, related_name='requerimentos', to='migratedbs.tiporesposta'),
        ),
        migrations.AddIndex(
            model_name='requerimento',
            index=models.Index(fields=['ano_requerimento', 'num_requerimento'], name='requeriment_ano_req_44dc0b_idx'),
        ),
    ]
